### ISSUE TITLE
Could you provide the documentation english version?

### ISSUE THREAD

**Issue by trocolit2** [jamesljlster/yoro#1]
Could you provide the software documentation English version?
I would like the test your solution with my private dataset and check the performance of accuracy and fps. 
Do you have any benchmark with the results of accuracy and fps?

**Comment by jameslai-dev** [comment]
Hello Tiago,
(Please correct me if I call you by the wrong part of name)

I'm very happy you are willing to test my project.
I currently don't have a formal benchmark of it, but I can provide some test results here.
The dataset I use is 'coating' dataset, which can be obtained from:  <https://drive.google.com/file/d/1FBhiYQWKvWbFCb3NXIB5D8G7X6xrV0XX/view>
As for annotation tool, please refer to: <https://github.com/jamesljlster/ican_mark>

The model can reach 1.0 mAP on evaluation set with YOLOv4 tiny backbone.
For real-time inference with webcam, FPS is around 16.63 on RTX 2060 (7% utility) and Ryzen 4800H (3.05 load average).

For runtime environment, a C++11 ABI compatible PyTorch and OpenCV is required.
I recommend building PyTorch on your development environment by yourself.
After depencencies preparation being done, execute ```pip install -v .``` on project root for compilation and installation.
If there is no any error occurrs and ```yoro``` package can be successfully imported in python interpreter, the setup is done.

Then you can prepare the coating dataset and execute ```trainer config/yolov4-tiny.yaml``` to reproduce my training result.
The dataset path is defined in config: <https://github.com/jamesljlster/yoro/blob/master/config/yolov4-tiny.yaml#L54>

For model inference, execute ```recaller yoro <exported_model_path> image <image_path>``` to test on image or execute ```recaller --help``` for detail usage.

I'm sorry the English documentation is not available yet, due to I have very limited free time nowadays.
If you need future support, please feel free to contact me via one of:
- Email: jamesljlster@gmail.com
- Discord: JamesLai#1527

**Comment by trocolit2** [comment]
Hi James! 
Thanks for your quick reply, and you wrote the correct part of my name!

Unfortunately, for my application is required at least 50 fps due to the dynamic environment, and hardware limitation...

Currently, we are using pure YOLO + a dedicated orientation estimation.
Like you, I am really busy now to spend some time improving, and contribute your solution. However, it is in my roadmap to improve and unify my method and test yours!

Thanks for your time and attention!

**Comment by jameslai-dev** [comment]
Hello Tiago,

Thanks for your feedback!
The FPS I report is low because my webcam is running on 30 FPS and the model can't run faster than it.
If I only test for model inference speed without any latency of image grabbing and result visualization, the FPS can be greater than 200.
However, it's always your rights to choose which method to use!

If you are interested in it, here is my test code:

```python
import time
import numpy as np
from yoro.api import YORODetector

if __name__ == '__main__':

    src = np.zeros((416, 416, 3), dtype=np.uint8)
    model = YORODetector('./coating_yolov4_tiny_epoch_2100.zip')

    # Warmup
    for i in range(100):
        model.detect(src, 0.7, 0.6)

    # Speed test
    startTime = time.time()
    counts = 1000
    for i in range(counts):
        model.detect(src, 0.7, 0.6)
    print('FPS:', counts / (time.time() - startTime))
```

You can also get the model file from my release page: <https://github.com/jamesljlster/yoro/releases/tag/v0.4.0>

I will continuously release new version of this solution and documentation when it reaches new millstone.
If you like my project, please star it and watch for the release!
